language: java

jdk: openjdk11

sudo: false

# before_install: cd src
  
script: mvn clean verify 

# publish code coverage after successful build
after_success:
  - bash <(curl -s https://codecov.io/bash)
